In [85]:
import numpy as np
a = np.arange(0,21)#等差數列0~20間隔1

even_a = a[0:21:2]#從上述數列取出偶數

three_multiple_a= a[3:21:3]#從上述數列取出3的倍數

In [87]:
print(a)
print(even_a)
print(three_multiple_a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 0  2  4  6  8 10 12 14 16 18 20]
[ 3  6  9 12 15 18]
