In [50]:
import numpy as np

In [63]:
array1 = np.array(range(30))
array2 = np.reshape(array1, (5, -1), order='F')
array3 = np.where(array2%6==1)

In [65]:
print(array1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [66]:
print(array2)

[[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]


In [67]:
print(array3)

(array([0, 1, 2, 3, 4], dtype=int64), array([5, 0, 1, 2, 3], dtype=int64))
